name: images-worker-versions-upload

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/images-worker/**'
      - '.github/workflows/images-worker-versions-upload.yaml'

permissions:
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Disable AppArmor
        # Ubuntu >= 23 has AppArmor enabled by default, which breaks Puppeteer.
        # See https://github.com/puppeteer/puppeteer/issues/12818 "No usable sandbox!"
        # this is taken from the solution used in Puppeteer's own CI: https://github.com/puppeteer/puppeteer/pull/13196
        # The alternative is to pin Ubuntu 22 or to use aa-exec to disable AppArmor for commands that need Puppeteer.
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
        shell: bash

      - uses: ./.github/actions/setup-ci

      - name: Upload to Cloudflare Workers
        id: upload
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: versions upload --config wrangler.jsonc
          workingDirectory: ./apps/images-worker
        env:
          BASIC_AUTH_USERNAME: ${{ secrets.IMAGES_WORKER_BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.IMAGES_WORKER_BASIC_AUTH_PASSWORD }}

      - name: Comment Preview URL
        uses: ./.github/actions/comment-preview-url
        with:
          name: "@taga3s/images-worker"
          target_url: ${{ steps.upload.outputs.deployment-url }}
          pr_number: ${{ github.event.number }}
